Command new
intel/he-toolkit pull request #107
Opened 2022-05-18 22:37 UTC by denCalderon

The command new will create a directory structure with some templates for files as README, cmake, etc

2022-05-23 14:03 UTC, hamishun submitted a review, later dismissed

2022-05-23 14:55 UTC, jlhcrawford commented on kit/command_new.py
> +        "set(CMAKE_CXX_STANDARD 17)\n"
Weren't we going to move these values (17 and 3.13) to some "constant" variables?

2022-05-25 17:57 UTC, jlhcrawford requested changes
Some typo/documentation changes. Otherwise, code looks good.

2022-05-25 17:57 UTC, jlhcrawford commented on kit/constants.py
> +    # cmakes properties
```suggestion
    # cmake properties
```

2022-05-25 17:57 UTC, jlhcrawford commented on kit/README.md
> +The command new can be used to create a new application. When it is executed
```suggestion
The command `new` can be used to create a new project. When it is executed
```

2022-05-25 17:57 UTC, jlhcrawford commented on kit/README.md
> +However, when the command is executed without `-–based-on`.
```suggestion
However, when the command is executed without `-–based-on`
```

2022-05-25 17:57 UTC, jlhcrawford commented on kit/README.md
> +And the following actions should be completed to build the new application:
```suggestion
The following actions should be completed to build the new application:
```

2022-05-25 17:57 UTC, jlhcrawford commented on kit/README.md
> +* Open CMakeLists.txt and uncomment the statements for find_package and target_link_libraries of the required library. If other dependencies are needed, for instance Threads, the file must be updated
```suggestion
* Open `CMakeLists.txt` and uncomment the statements for `find_package` and `target_link_libraries` of the required library. If other dependencies are needed, for instance `Threads`, the file must be updated to include and compile them.
```

2022-05-25 17:57 UTC, jlhcrawford commented on kit/README.md
> +* Open the toml file inside the recipes directory and replace `-DFLAG=TBD` with the required flags
```suggestion
* Open the toml file inside the recipes directory and replace `-DFLAG=TBD` with the desired CMake flags for your project.
```

2022-05-25 17:57 UTC, jlhcrawford commented on kit/README.md
> +* Add the code of the new application in the .cpp and .h files created by the command
```suggestion
* Add and/or write the code of the new application in the `.cpp` and `.h` files created by the command.
```

2022-05-25 19:46 UTC, hamishun requested changes

2022-05-25 19:46 UTC, hamishun commented on docker/Dockerfile.toolkit
> +    . docker/runners.sh
If this does not work, better to revert the change

2022-05-25 20:03 UTC, hamishun approved these changes

2022-05-26 14:35 UTC, jlhcrawford approved these changes

2022-05-26 14:37 UTC, merged