Rebuild or/and reinstall a project after changes in the code
intel/he-toolkit pull request #112
Opened 2022-05-31 18:39 UTC by denCalderon

Current implementation skips build/install if they were already executed and marked as success, so the user can not rebuild/reinstall the program after doing changes in the source code. Changes fixed this issue.

2022-06-07 16:06 UTC, jlhcrawford approved these changes

2022-06-07 17:04 UTC, hamishun requested changes
I think the new behaviour should only happen is a -f and/or --force is supplied

2022-06-08 13:25 UTC, hamishun approved these changes

2022-06-08 13:30 UTC, jlhcrawford approved these changes

2022-06-08 13:32 UTC, merged