Add decorator to load config file
intel/he-toolkit pull request #134
Opened 2022-07-18 20:08 UTC by denCalderon

2022-07-20 10:43 UTC, hamishun requested changes
@denCalderon we need some unit tests for the new decorator

2022-07-21 13:29 UTC, hamishun approved these changes

2022-07-21 19:18 UTC, jlhcrawford requested changes

2022-07-21 19:18 UTC, jlhcrawford commented on kit/utils/config.py
> +    """Error for when config file """
Is this comment incomplete?

2022-07-22 16:26 UTC, jlhcrawford approved these changes

2022-07-22 16:27 UTC, merged