Unit test refactoring
intel/he-toolkit pull request #140
Opened 2022-07-29 21:56 UTC by denCalderon

2022-07-31 21:59 UTC, hamishun requested changes

2022-07-31 21:59 UTC, hamishun commented on tests/common_utils.py
> +    return out.stdout.decode("utf-8"), out.stderr.decode("utf-8")
this instead allows you to use the existing output object and refer to stdout stderr and returncode without defining a different object or returning using tuples
```suggestion
def execute_process(cmd: str) -> str:
    return run(split(cmd), encoding="utf-8", capture_output=True)
```

2022-07-31 21:59 UTC, hamishun commented on kit/utils/files.py
> +def create_default_workspace(dir_path: str = "~/") -> Path:
```suggestion
def create_default_workspace(dir_path: str = "~") -> Path:
```

2022-07-31 21:59 UTC, hamishun commented on tests/common_utils.py
> +        run(cmd, stdout=f)
You use a subprocess for this instead of python's own file operations? `f.write(f"repo_location = {path}\n")` would work just as well no?

2022-07-31 21:59 UTC, hamishun commented on tests/input_files/test.toml
> +version = "1.2.3"
does this file not need the ! subs anymore? how come?

2022-07-31 21:59 UTC, hamishun commented on tests/test_util_spec.py
> +    Spec.recipe_arg_dict = {}
Seems strange that we save something variable to a class var instead of an instance var.

2022-08-01 15:54 UTC, denCalderon commented on tests/input_files/test.toml
> +version = "1.2.3"
there is default values for those class members

2022-08-01 16:24 UTC, denCalderon commented on tests/test_util_spec.py
> +    Spec.recipe_arg_dict = {}
code was updated

2022-08-01 16:25 UTC, denCalderon commented on tests/common_utils.py
> +        run(cmd, stdout=f)
code was updated

2022-08-01 16:25 UTC, denCalderon commented on kit/utils/files.py
> +def create_default_workspace(dir_path: str = "~/") -> Path:
code was updated

2022-08-01 18:49 UTC, hamishun approved these changes

2022-08-01 18:53 UTC, hamishun requested changes
ci files need updating to run tests in parallel

2022-08-01 22:23 UTC, hamishun approved these changes

2022-08-02 15:52 UTC, jlhcrawford requested changes
Found typos in comments. Otherwise, the code looks ok.

2022-08-02 15:52 UTC, jlhcrawford commented on tests/test_integration_install.py
> +    # Test list command after isntall
```suggestion
    # Test list command after install
```

2022-08-02 15:52 UTC, jlhcrawford commented on tests/test_integration_wrong_inputs.py
> +    the config file is a symlink"""
```suggestion
    the recipe file is a symlink"""
```

2022-08-02 15:52 UTC, jlhcrawford commented on tests/test_integration_wrong_inputs.py
> +    the recipe file has an float value instead of a string"""
```suggestion
    the recipe file contains a float value instead of a string"""
```

2022-08-02 15:52 UTC, jlhcrawford commented on tests/test_integration_healg.py
> +    """Verify that gen-primes cmd is excuted correctly when
```suggestion
    """Verify that gen-primes cmd is executed correctly when
```

2022-08-02 16:18 UTC, jlhcrawford approved these changes

2022-08-02 16:22 UTC, merged