Plugins
intel/he-toolkit pull request #143
Opened 2022-08-26 20:57 UTC by denCalderon

Add functionality to handle third party plugins

2022-08-27 19:54 UTC, hamishun requested changes

2022-08-27 19:54 UTC, hamishun commented on kit/commands/init.py
> +        "if [ -n $(type -p register-python-argcomplete3) ]; then\n"
Not sure if this is a good idea. I think this is for the argcomplete that is installed by apt.

2022-08-27 19:54 UTC, hamishun commented on kit/hekit.py
> +    register_subparser(subparsers, get_plugins_by_state(), PluginsConfig.ROOT_DIR)
I don't think it is a good idea to have `get_plugins_by_state` have a default state here. It is not obvious reading the code here that the default is enabled. Just be explicit for clarity.

2022-08-30 12:11 UTC, hamishun requested changes

2022-08-30 12:11 UTC, hamishun commented on tests/test_util_files.py
> +    file = f"{get_toolkit_path}/tests/input_files/default_symlink.config"
```suggestion
    file = get_toolkit_path / "tests/input_files/default_symlink.config"
```

2022-08-30 12:11 UTC, hamishun commented on kit/commands/new.py
>      project_path = project_path / "projects" / f"{project_name}"
```suggestion
    project_path = project_path / "projects" / project_name
```

2022-08-31 08:24 UTC, hamishun submitted a review, later dismissed

2022-08-31 10:53 UTC, jlhcrawford requested changes
Some typos but there is a duplicate plugin pytest that needs changing.

2022-08-31 10:53 UTC, jlhcrawford commented on kit/utils/files.py
> +    """Load a toml file and returns its content as a dict"""
```suggestion
    """Load a toml file and return its content as a dict"""
```

2022-08-31 10:53 UTC, jlhcrawford commented on tests/test_cmd_plugins.py
> +    """Verify that the SW return a dict
```suggestion
    """Verify that the SW returns a dict
```

2022-08-31 10:53 UTC, jlhcrawford commented on tests/test_cmd_plugins.py
> +    """Verify that the SW returns the correct plugin type"""
```suggestion
    """Verify that the SW returns the correct plugin type (directory)"""
```

2022-08-31 10:53 UTC, jlhcrawford commented on tests/test_cmd_plugins.py
> +    """Verify that the SW returns the correct plugin type"""
```suggestion
    """Verify that the SW returns the correct plugin type (tarball)"""
```

2022-08-31 10:53 UTC, jlhcrawford commented on tests/test_cmd_plugins.py
> +    """Verify that the SW returns the correct plugin type"""
```suggestion
    """Verify that the SW returns the correct plugin type (zip file)"""
```

2022-08-31 10:53 UTC, jlhcrawford commented on tests/test_cmd_plugins.py
> +def test_update_plugin_state_already_disabled(mocker):
This test does not test for a disabled plugin but an enabled one like the test above.

2022-08-31 10:53 UTC, jlhcrawford commented on tests/test_cmd_plugins.py
> +    mockers.mock_print.assert_called_with("All Plugins were uninstalled successfully")
```suggestion
    mockers.mock_print.assert_called_with("All plugins were uninstalled successfully")
```

2022-08-31 10:53 UTC, jlhcrawford commented on kit/commands/plugin.py
> +        print("All Plugins were uninstalled successfully")
```suggestion
        print("All plugins were uninstalled successfully")
```

2022-08-31 16:46 UTC, jlhcrawford approved these changes

2022-08-31 16:51 UTC, merged