Plugins versioning
intel/he-toolkit pull request #144
Opened 2022-09-05 23:13 UTC by denCalderon

2022-09-06 15:33 UTC, hamishun requested changes

2022-09-06 15:33 UTC, hamishun commented on kit/commands/plugin.py
> +PluginsDataList = List[Dict[str, str]]
Is the Dict[str, str] inside not some other known type alias?

2022-09-06 15:33 UTC, hamishun commented on kit/commands/plugin.py
> +    exp_file = ""
not sure you need all these defaults defined here. Most of the time in pytohn you can create when you return. I also note that the if elif can just be ifs with returns. if...return if...return

2022-09-06 15:33 UTC, hamishun commented on kit/commands/plugin.py
> +    exp_file = ""
just make sure you always return the correct type :)

2022-09-06 15:33 UTC, hamishun commented on kit/commands/plugin.py
> +                continue
is this logic correct? if we say 'yes' should it not intall it?

2022-09-06 15:33 UTC, hamishun commented on tests/test_cmd_plugins.py
> +
```suggestion
        with toml_file.open("w") as f:
            f.write("[plugin]\n"
                       f'name = "{plugin_name}"\n'
                       'version = "1.0.0"\n'
                       'start = "plugin.py"\n'
                    )
```

2022-09-06 15:33 UTC, hamishun commented on tests/test_cmd_plugins.py
> +
String literals next to each other concat. Many languages are like this. Formatting may fail though if you accept suggestion as is.

2022-09-06 15:33 UTC, hamishun commented on tests/test_cmd_plugins.py
> +            f.write(f'state = "{state}"\n')
Again, should only need a single func call.

2022-09-08 12:15 UTC, hamishun requested changes

2022-09-08 12:15 UTC, hamishun commented on kit/commands/plugin.py
> +def check_plugin_structure(
This functions strcuture is confused when checking PluginType. Either have if...return if...return ... or if...elif...elif...else, but not both

2022-09-08 12:15 UTC, hamishun commented on kit/commands/plugin.py
> +                    with f.extractfile(toml_file) as file:  # type: ignore[union-attr]
```suggestion
                    
                    # Read the toml file and check that the file
                    # defined in "start" is present
                    file = f.extractfile(toml_file)
                    if file == None:
                        raise TypeError(...)
                    with file: 
```
This fixes the mypy issue. union-attr is because extractfile returns an Optional[IO] type. In other words it is a union of a type IO and None. mypy checks that all the types of the union have the attribute being called.

2022-09-08 12:15 UTC, hamishun commented on kit/commands/plugin.py
> +                    with f.extractfile(toml_file) as file:  # type: ignore[union-attr]
add appropriate msg to the raised error. dont just accept the suggestion :)

2022-09-08 15:01 UTC, hamishun approved these changes

2022-09-08 15:42 UTC, jlhcrawford requested changes

2022-09-08 15:42 UTC, jlhcrawford commented on tests/test_util_spec.py
> +            "\n"  # Parser inserts this new line
I understand why you have used single quotes instead of double quotes but it is a good idea to keep the type of quotes consistent across the strings here for readability.
Change lines 282, 284, and 297 to also have single quotes.

2022-09-08 15:42 UTC, jlhcrawford commented on tests/test_cmd_new.py
> +        )
Make the quote type consistent in this function call.
Change lines 105 and 110 to use single quotes.

2022-09-08 15:42 UTC, jlhcrawford commented on kit/commands/plugin.py
> +        elif plugin_name in config_dict.keys():
What happens if the plugin name is not in the dictionary?
Should we have an `else` statement in this logic?

2022-09-08 17:44 UTC, jlhcrawford approved these changes

2022-09-08 17:46 UTC, merged