Plugins docs
intel/he-toolkit pull request #146
Opened 2022-09-12 22:25 UTC by denCalderon

2022-09-13 16:13 UTC, hamishun requested changes
format tests are failing.

2022-09-13 16:13 UTC, hamishun commented on README.md
> +  - [Third Party Plugins](#third-party-plugins)
This is a feature. Should appear before Contributuions in its own section.

2022-09-13 16:13 UTC, hamishun commented on README.md
> +## Third Party Plugins
This is a feature. Should appear before Contributuions in its own section.

2022-09-14 14:47 UTC, jlhcrawford commented on kit/PLUGINS.md
> +uses the arguments defined in the previous step.
I am not sure I understand what this paragraph means.

2022-09-14 14:47 UTC, jlhcrawford commented on kit/PLUGINS.md
> +it must be the same as the `name` value defined in the TOML file. This
Is this true? The name of the directory must match the plugin name?
If so the example you provided above doesn't follow this rule.

2022-09-14 18:34 UTC, hamishun approved these changes

2022-09-14 18:52 UTC, jlhcrawford approved these changes

2022-09-14 18:53 UTC, merged