Add new command: plugins refresh
intel/he-toolkit pull request #147
Opened 2022-09-16 20:45 UTC by denCalderon

2022-09-20 16:32 UTC, jlhcrawford requested changes
Implementation looks fine. Mainly documentation/clarity of implementation.

2022-09-20 16:32 UTC, jlhcrawford commented on kit/utils/subparsers.py
> +    """Return the choices of the argument parser"""
```suggestion
    """Return the choices (list of plugin names) of the argument parser"""
```

2022-09-20 16:32 UTC, jlhcrawford commented on kit/commands/plugin.py
> +    """Verify that trser_choices_he plugin argument is unique"""
Maybe change this to something like "Verify that all plugin names are unique"

2022-09-20 16:32 UTC, jlhcrawford commented on kit/commands/plugin.py
> +    # verify it contains only one choice
```suggestion
    # verify the plugin name only appears once
```

2022-09-20 16:36 UTC, jlhcrawford commented on kit/PLUGINS.md
> +Execute the following command to synchronize the information in plugin
```suggestion
Execute the following command to synchronize the information in the plugin
```

2022-09-20 20:57 UTC, denCalderon commented on tests/test_cmd_plugins.py
> +def test_are_plugin_args_correct():
this is already resolved in the lastest version

2022-09-20 20:57 UTC, denCalderon commented on tests/test_cmd_plugins.py
> +def test_refresh_plugins():
this is already resolved in the lastest version

2022-09-21 13:44 UTC, hamishun requested changes

2022-09-21 13:44 UTC, hamishun commented on kit/utils/constants.py
> +    # HE comands
```suggestion
    # hekit core commands
```

2022-09-21 13:44 UTC, hamishun commented on kit/utils/constants.py
> +
Maybe a set would be better?
```suggestion
    HEKIT_COMMANDS = {
        "check-dependencies",
        "docker-build",
        "init",
        "install",
        "build",
        "fetch",
        "list",
        "new",
        "plugins",
        "remove",
        "algebras",
        "gen-primes",
    }

```

2022-09-21 17:26 UTC, denCalderon commented on kit/utils/constants.py
> +    # HE comands
updated

2022-09-21 17:26 UTC, denCalderon commented on kit/utils/constants.py
> +
updated

2022-09-21 17:27 UTC, denCalderon commented on tests/test_cmd_plugins.py
> +    the argument name is fine"""
updated

2022-09-21 17:27 UTC, denCalderon commented on tests/test_cmd_plugins.py
> +    there is not argument name in the list"""
updated

2022-09-21 18:07 UTC, jlhcrawford requested changes

2022-09-21 18:07 UTC, jlhcrawford commented on kit/utils/constants.py
> +    # Hekit core commands
```suggestion
    # hekit core commands
```

2022-09-21 20:45 UTC, hamishun approved these changes

2022-09-22 14:13 UTC, jlhcrawford approved these changes

2022-09-22 14:39 UTC, merged