Initial configurable PSI deployment
intel/he-toolkit pull request #149
Opened 2022-09-23 15:27 UTC by jlhcrawford

Initial commit for the configurable PSI deployment.
Includes
- source code in `deployments/config_psi/psi`
- Gtest unit tests in `deployments/config_psi/psi/tests`
- python scripts for encode and decode in `deployments/config_psi/scripts`
- pytests for scripts in `deployments/config_psi/scripts/tests`
- pytests for `deployments/config_psi/tests`
- Initial version of configurable PSI README (`deployments/config_psi/README.md`).
- Recipe file for building configurable PSI deployment and required dependencies `recipes/config-psi.toml`

2022-09-26 10:46 UTC, hamishun requested changes

2022-09-26 10:46 UTC, hamishun commented on deployments/config_psi/README.md
> +directory contains code which performs the core PSI operation. The `scrips`
```suggestion
directory contains code which performs the core PSI operation. The `scripts`
```

2022-09-26 10:46 UTC, hamishun commented on deployments/config_psi/README.md
> +encoding (default), and server encoding when supplied the `--server` flag.
```suggestion
encoding (default) and server encoding when supplied the `--server` flag.
```

2022-09-26 10:46 UTC, hamishun commented on deployments/config_psi/README.md
> +```
Is TOML supported here. Github markdown may not at the mo, but worth checking.

2022-09-26 10:46 UTC, hamishun commented on deployments/config_psi/psi/tests/main.cpp
> +// *****************************************************************************
Needs update

2022-09-27 12:39 UTC, hamishun requested changes

2022-09-27 12:39 UTC, hamishun commented on deployments/config_psi/scripts/README.md
> +`decode.py` decodes data
We should explain how these work

2022-09-28 17:32 UTC, jlhcrawford commented on deployments/config_psi/scripts/README.md
> +`decode.py` decodes data
Description added

2022-09-30 13:59 UTC, hamishun approved these changes

2022-09-30 14:38 UTC, merged