Add/ubuntu22.04
intel/he-toolkit pull request #155
Opened 2022-10-05 20:29 UTC by mkilari1

Adding ubuntu 22.04 tests to CI

2022-10-10 18:33 UTC, jlhcrawford requested changes
There is an inconsistency with the HElib, SEAL, and PALISADE builds.
HElib and PALISADE:
Ubuntu 20.04 - clang 10
Ubuntu 20.04 - gcc 10
Ubuntu 20.04 - clang (what version is this?)
Ubuntu 22.04 - clang (what version is this?)
Ubuntu 22.04 - gcc 10

SEAL:
Ubuntu 20.04 - clang 10
Ubuntu 20.04 - gcc 10
Ubuntu 22.04 - clang 14
Ubuntu 22.04 - gcc 10

2022-10-10 18:33 UTC, jlhcrawford commented on .github/workflows/github-ci.yml
> +        c_compiler: [clang-10, gcc-10, clang]
This matrix tests clang-10 and clang on Ubuntu 20.04. What is the default clang on Ubuntu 20.04?

2022-10-10 18:33 UTC, jlhcrawford commented on .github/workflows/github-ci.yml
> +        c_compiler: [clang-10, gcc-10, clang]
Same as previous comment. I've noticed you are testing clang and clang-10 on Ubuntu 20.04. Are you supposed to do this? Because the SEAL matrix explicitly tests 
Ubuntu 20.04 - clang-10
Ubuntu 20.04 - gcc-10
Ubuntu 22.04 - clang-14
Ubuntu 22.04 - gcc-10

2022-10-10 18:34 UTC, jlhcrawford commented on .github/workflows/github-ci.yml
>          include: # use clang++ and gcc+ with clang only
Also please change this comment to be something clearer in terms of the intent of the `include` option.

2022-11-02 14:04 UTC, hamishun commented on .github/workflows/github-ci.yml
> +          # Clang-10 not pre-installed on Ubuntu-22
```suggestion
          # clang-14 is default on Ubuntu-22
```

2022-11-02 14:05 UTC, hamishun commented on .github/workflows/github-ci.yml
> +          # Clang-10 not pre-installed on Ubuntu-22
```suggestion
          # clang-14 is defaul on Ubuntu-22
```

2022-11-02 18:57 UTC, jlhcrawford requested changes

2022-11-02 18:57 UTC, jlhcrawford commented on .github/workflows/README.md
> +
What about the GCC versions we are testing? Also can you add the python version we are testing.

2022-11-02 18:57 UTC, jlhcrawford commented on README.md
> +* HE Toolkit `SEAL` examples currently don't work with `clang-12`
```suggestion
* HE Toolkit `SEAL` examples currently do not work with `clang-12`
```

2022-11-02 18:57 UTC, jlhcrawford commented on README.md
> +* HE Toolkit `SEAL` examples currently don't work with `clang-12` and `clang-13`
```suggestion
* HE Toolkit `SEAL` examples currently do not work with `clang-12` and `clang-13`
```

2022-11-03 15:57 UTC, jlhcrawford requested changes

2022-11-03 15:57 UTC, jlhcrawford commented on .github/workflows/github-ci.yml
> +        c_compiler: [clang-10, gcc-10, clang-12, gcc-11]
Where's clang 14? We should always be testing the default compiler.

2022-11-04 18:20 UTC, hamishun requested changes

2022-11-04 18:20 UTC, hamishun commented on .github/workflows/README.md
> +</br>
What is with these HTML tags?

2022-11-04 18:20 UTC, hamishun commented on README.md
> +
We should only test clang-14 on ubuntu 22.04

2022-11-04 18:22 UTC, ajagann commented on .github/workflows/README.md
> +</br>
To get some spacing between the tables

2022-11-04 18:39 UTC, mkilari1 commented on README.md
> +
Jack recommended that we also test Clang-12 and clang-13 on Ubuntu 22.04. So I have it documented as part of known issues.

2022-11-04 20:48 UTC, hamishun approved these changes

2022-11-07 14:44 UTC, jlhcrawford approved these changes

2022-11-07 14:45 UTC, merged