Test/config psi
intel/he-toolkit pull request #156
Opened 2022-10-17 16:03 UTC by mkilari1

Added config PSI tests to CI and added badge to main

2022-10-18 17:12 UTC, denCalderon requested changes
Minor changes and there are some missing tests

2022-10-18 17:12 UTC, denCalderon commented on .github/workflows/github-ci.yml
> +          pytest deployments/config_psi/scripts/tests/
The following test is missing:

pytest deployments/config_psi/tests/

2022-10-20 20:08 UTC, denCalderon approved these changes

2022-10-20 20:10 UTC, jlhcrawford approved these changes

2022-10-20 20:17 UTC, merged