Add option of editing the .bashrc
intel/he-toolkit pull request #157
Opened 2022-10-17 22:25 UTC by denCalderon

Add an option  asking the user if they would like to edit their configuration file. If not then we can tell the user what lines they need to add.

2022-10-18 20:45 UTC, jlhcrawford requested changes
This looks very good. Just some very minor tweaks.

2022-10-18 20:45 UTC, jlhcrawford commented on kit/commands/init.py
> +    """Return the lines that will be added in the rc file"""
```suggestion
    """Return the lines that will be added to the rc file"""
```

2022-10-18 20:45 UTC, jlhcrawford commented on kit/commands/init.py
> +            f"Please, execute the following actions manually:\n"
```suggestion
            f"Please execute the following actions manually:\n"
```

2022-10-18 20:45 UTC, jlhcrawford commented on kit/commands/init.py
> +            f"3. Source your shell init file as: source {rc_file}"
```suggestion
            f"3. Source your shell config file with: source {rc_file}"
```

2022-10-18 20:45 UTC, jlhcrawford commented on kit/commands/init.py
> +    # Backup the shell init file
```suggestion
    # Backup the shell config file
```

2022-10-18 20:45 UTC, jlhcrawford commented on tests/test_integration_init.py
> +        f"\n3. Source your shell init file as: source {tmp_path}/.mybashfile"
```suggestion
        f"\n3. Source your shell config file with: source {tmp_path}/.mybashfile"
```

2022-10-18 20:45 UTC, jlhcrawford commented on kit/commands/init.py
> +        f"{rc_new_content}\n"
```suggestion
        f"{rc_new_content}\n"
        "NOTE: a backup file will be created.\n"
```

2022-10-18 21:17 UTC, denCalderon commented on kit/commands/init.py
> +            f"Please, execute the following actions manually:\n"
updated

2022-10-18 21:17 UTC, denCalderon commented on kit/commands/init.py
> +            f"3. Source your shell init file as: source {rc_file}"
updated

2022-10-18 21:18 UTC, denCalderon commented on kit/commands/init.py
> +    # Backup the shell init file
updated

2022-10-18 21:24 UTC, denCalderon commented on kit/commands/init.py
> +        f"{rc_new_content}\n"
updated

2022-10-20 14:26 UTC, hamishun commented on kit/commands/init.py
> +    lines = ["\n", content, "\n"]
Why are the tags removed?

2022-10-20 14:59 UTC, hamishun requested changes

2022-10-20 14:59 UTC, hamishun commented on kit/commands/init.py
> +    )
```suggestion
    eval_lines = (
        'if [ -n "$(type -p register-python-argcomplete)" ]; then\n'
        '  eval "$(register-python-argcomplete hekit)"\n'
        'fi\n'
    )
```

2022-10-20 14:59 UTC, hamishun commented on kit/commands/init.py
> +            f"Please execute the following actions manually:\n"
```suggestion
            "Please execute the following actions manually:\n"
```

2022-10-20 15:03 UTC, hamishun commented on kit/commands/init.py
> +    lines = ["\n", content, "\n"]
I see the are inserted elsewhere, ok

2022-10-21 09:37 UTC, jlhcrawford commented on kit/commands/init.py
> +    print("Please, source your shell config file as follows")
```suggestion
    print("Please source your shell config file as follows")
```

2022-10-21 12:39 UTC, jlhcrawford approved these changes

2022-10-21 14:18 UTC, hamishun approved these changes

2022-10-21 14:21 UTC, merged