Ci/python 3.9
intel/he-toolkit pull request #166
Opened 2022-11-14 21:40 UTC by mkilari1

Added python version 3.9 on Ubuntu 20.04 and python version 3.10 on Ubuntu 22.04

2022-11-15 13:20 UTC, hamishun approved these changes

2022-11-15 13:28 UTC, hamishun requested changes
a few minor updates required

2022-11-15 18:39 UTC, mkilari1 commented
> a few minor updates required

can you let me know what kind of updates are needed?

2022-11-16 16:03 UTC, hamishun approved these changes

2022-11-16 16:23 UTC, merged