separate out existing tools
intel/he-toolkit pull request #168
Opened 2022-11-28 22:32 UTC by hamishun

2022-11-28 23:06 UTC, hamishun commented
A few integration tests I missed to separate, so don't merge, yet.

2022-11-29 10:52 UTC, hamishun commented
OK separation done.

2022-11-29 16:16 UTC, jlhcrawford requested changes

2022-11-29 16:16 UTC, jlhcrawford commented on kit/tools/README.md
> +The tools commands for `hekit` contain useful commands to finds HE parameters
```suggestion
The tools for `hekit` consist of useful commands for finding HE parameters
```

2022-11-29 16:16 UTC, jlhcrawford commented on kit/tools/README.md
> +based on user constraints. Next sections describe the details about them.
```suggestion
based on user constraints. The following sections describe their details and usage.
```

2022-11-29 16:16 UTC, jlhcrawford commented on kit/tools/README.md
> +m] where n and m are positive integers
```suggestion
m] where n and m are positive integers.
```

2022-12-06 20:04 UTC, denCalderon reviewed
minor changes

2022-12-07 15:54 UTC, jlhcrawford requested changes

2022-12-07 15:54 UTC, jlhcrawford commented on tests/test_integration_algebras.py
> +    """Verify that gen-primes cmd is executed correctly when
```suggestion
    """Verify that the algebras cmd is executed correctly when
```

2022-12-07 15:54 UTC, jlhcrawford commented on tests/test_integration_algebras.py
>      cmd = f"{hekit_path} -p 7 -d {sys.maxsize} --no-header"
```suggestion
    cmd = f"{hekit_path} algebras -p 7 -d {sys.maxsize} --no-header"
```

2022-12-07 15:54 UTC, jlhcrawford commented on tests/test_integration_algebras.py
>      """Verify that gen-primes cmd triggers an error when
```suggestion
    """Verify that the algebras cmd triggers an error when
```

2022-12-07 15:54 UTC, jlhcrawford commented on tests/test_integration_algebras.py
> +    """Verify that gen-primes cmd is executed correctly when
```suggestion
    """Verify that the algebras cmd is executed correctly when
```

2022-12-07 15:54 UTC, jlhcrawford commented on tests/test_integration_algebras.py
> +    """Verify that gen-primes cmd is executed correctly when
```suggestion
    """Verify that the algebras cmd is executed correctly when
```

2022-12-07 15:54 UTC, jlhcrawford commented on tests/test_integration_algebras.py
>      """Verify that gen-primes cmd triggers an error when
```suggestion
    """Verify that the algebras cmd triggers an error when
```

2022-12-07 15:54 UTC, jlhcrawford commented on tests/test_integration_algebras.py
> +    """Verify that gen-primes cmd is executed correctly when
```suggestion
    """Verify that the algebras cmd is executed correctly when
```

2022-12-07 15:54 UTC, jlhcrawford commented on tests/test_integration_algebras.py
> +    """Verify that algebras cmd is executed correctly when
```suggestion
    """Verify that the algebras cmd is executed correctly when
```

2022-12-07 15:54 UTC, jlhcrawford commented on tests/test_integration_algebras.py
> +    """Verify that gen-primes cmd is executed correctly
```suggestion
    """Verify that the algebras cmd is executed correctly
```

2022-12-07 17:31 UTC, merged