Deprecate support on ubuntu20.04
intel/he-toolkit pull request #181
Opened 2023-08-21 19:35 UTC by faberga

## Proposed changes

Deprecate support of HE-Toolkit on Ubuntu 20.04

The HE-Toolkit is now only supported on Ubuntu 22.04 with Clang 14.x and GCC 11.x

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you are unsure about any of them, do not hesitate to ask. We are
here to help! This is simply a reminder of what we are going to look for before
merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/intel/he-toolkit/tree/main#contributing) section
- [x] Current formatting and unit tests / base functionality passes locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did, what alternatives you
considered, etc.

2023-08-21 22:53 UTC, hamishun requested changes

2023-08-21 22:53 UTC, hamishun commented on README.md
> +g++ = 11.x or clang = 14.x
```suggestion
g++ == 11.x or clang == 14.x
```

2023-08-21 22:53 UTC, hamishun commented on README.md
>  cmake >= 3.13
```suggestion
cmake >= 3.22
```

2023-08-21 22:53 UTC, hamishun commented on README.md
> +gmp 1.5.x  (optional if using HElib)
```suggestion
gmp == 1.5.x  (optional if using HElib)
```

2023-08-21 22:53 UTC, hamishun commented on docker/runners.sh
> +  __run_cmd "$HEKIT_EXAMPLES"/psi/build/psi --server "$HEKIT_EXAMPLES"/psi/build/datasets/fruits.set "$*"
why was this necessary?

2023-08-22 12:36 UTC, hamishun commented on .github/workflows/github-ci.yml
> +          pip3 install toml pydantic==1.10.4 pytest
Maybe we should not delay just install from the dev requirements file and version the deps there. This may be overkill for some setups but on balance won't delay much. 
```
pip3 install -r dev_reqs.txt
```

2023-08-22 12:42 UTC, hamishun commented on docker/runners.sh
> +  __run_cmd "$HEKIT_EXAMPLES"/psi/build/psi --server "$HEKIT_EXAMPLES"/psi/build/datasets/fruits.set "$*"
`"$@"` and `"$*"` have different meanings. That is why the former tends to be used to make sure that args are forwarded correctly.

2023-08-22 12:42 UTC, faberga commented on README.md
> +gmp 1.5.x  (optional if using HElib)
Well, the right GMP for anything >= icelake is the upstream GMP that has not been versioned yet and it is likely to be 1.6.x :-(
Having said that let's go with the base version 1.5.x

2023-08-22 12:42 UTC, faberga commented on README.md
> +gmp 1.5.x  (optional if using HElib)
I've committed the suggestion.

2023-08-22 12:44 UTC, faberga commented on docker/runners.sh
> +  __run_cmd "$HEKIT_EXAMPLES"/psi/build/psi --server "$HEKIT_EXAMPLES"/psi/build/datasets/fruits.set "$*"
that was the complaint of shellchek

2023-08-22 12:46 UTC, faberga commented on .github/workflows/github-ci.yml
> +          pip3 install toml pydantic==1.10.4 pytest
let's get this PR on, so we can the dockerfiles updated. After that we can have another PR to introducer a requirements file.

2023-08-22 12:47 UTC, hamishun commented on .github/workflows/github-ci.yml
> +          pip3 install toml pydantic==1.10.4 pytest
the file already exists just needs the version added there and these lines changed, but ok

2023-08-22 12:50 UTC, faberga commented on docker/runners.sh
> +  __run_cmd "$HEKIT_EXAMPLES"/psi/build/psi --server "$HEKIT_EXAMPLES"/psi/build/datasets/fruits.set "$*"
well, apparently we can use a "# shellcheck disable=blablabla" on the line with the error and keep the original "$@"

2023-08-22 12:53 UTC, hamishun commented on docker/runners.sh
> +  __run_cmd "$HEKIT_EXAMPLES"/psi/build/psi --server "$HEKIT_EXAMPLES"/psi/build/datasets/fruits.set "$*"
`"$@"` will forward correctly. `"$*"` will not.

2023-08-22 13:06 UTC, hamishun approved these changes

2023-08-22 13:22 UTC, merged