Update secure query documentation
intel/he-toolkit pull request #49
Opened 2021-09-09 02:43 UTC by skmono

Added detailed description to secure-query example
Authored by: jobottle <jeremy.bottleson@intel.com>

2021-09-09 11:28 UTC, jlhcrawford requested changes
A few typos and minor suggestions. We should really be pointing to the `homenc` version of HElib.

Also the example output looks strange having times of 0.0 seconds. It makes the lookup operation look like it is instantaneous. I'd suggest changing this.

2021-09-09 11:28 UTC, jlhcrawford commented on he-samples/examples/secure-query/README.md
> +[HELib country db lookup sample](https://github.com/IBM-HElib/HElib/tree/master/examples/BGV_country_db_lookup)
```suggestion
[HELib country db lookup sample](https://github.com/homenc/HElib/tree/master/examples/BGV_country_db_lookup)
```

2021-09-09 11:28 UTC, jlhcrawford commented on he-samples/examples/secure-query/README.md
> +[Fermat's Little Theorem](https://en.wikipedia.org/wiki/Fermat%27s_little_theorem)
```suggestion

[Fermat's Little Theorem](https://en.wikipedia.org/wiki/Fermat%27s_little_theorem)

```

2021-09-09 11:28 UTC, jlhcrawford commented on he-samples/examples/secure-query/README.md
> +For this example database keys are assumed to be char strings. With the default options they are encoded into 2 4bit chunks. This is done so that each chunk can be represented by the plain modulus of
```suggestion
For this example, database keys are assumed to be char strings. With the default options, they are encoded into 2 4bit chunks. This is done so that each chunk can be represented by the plain modulus of 17. The secure query lookup algorithm is based on using Fermat's little theorem to generate a mask from the query and for each database entry's key. This results in mask values of 1 for matches and 0 for non matches. This mask is then multiplied against the database entry value which is accumulated for all entries and returned. For this sample it is required that all entries possess a unique key.
```

2021-09-09 11:28 UTC, jlhcrawford commented on he-samples/examples/secure-query/README.md
> +The sample also supports specifying custom encryption parameters and input options. This can be useful to test more secure settings as well as to adjust keylength to support different database files.
```suggestion
The sample also supports specifying custom encryption parameters and input options. This can be useful to test more secure settings as well as to adjust key length to support different database files.
```

2021-09-09 11:28 UTC, jlhcrawford commented on he-samples/examples/secure-query/README.md
> + - Input database: us_state_capitals.csv (Has 50 entries consisting of key:value (state name : Capitol name) First letter capitalized.
```suggestion
 - Input database: us_state_capitals.csv (Has 50 entries consisting of key:value (state name : Capital name) First letter capitalized.
```

2021-09-09 11:28 UTC, jlhcrawford commented on he-samples/examples/secure-query/README.md
> +	Records searched per second: 0
Why are the times 0 seconds? Was it really this fast?

2021-09-09 11:28 UTC, jlhcrawford commented on he-samples/examples/secure-query/README.md
> + - Main.cpp Simple program which creates an instance of SQClient with either default or user specified encryption parameters, an instance of SQServer is then also initialized with the chosen paramete
```suggestion
 - Main.cpp Program which creates an instance of SQClient with either default or user specified encryption parameters, an instance of SQServer is then also initialized with the chosen parameters. Next the application reads in a set of key/value pairs from a user specified csv file and encrypts them using the HE context. The user is then prompted to enter a search key and the results of the search are then displayed.
```

2021-09-09 12:15 UTC, faberga requested changes
Hi Jeremy, 
Since this demo was inspired by the BGV Country DB lookup that ships with HElib, I would suggest you added an "Acknowledgement" section:

## Acknowledgement
This database lookup example is a derived port of the the BGV Country Lookup example code that ships with [HElib ](https://github.com/homenc/HElib) and can be found [here](https://github.com/homenc/HElib/tree/master/examples/BGV_country_db_lookup).

2021-09-09 14:25 UTC, fboemer commented on he-samples/examples/secure-query/README.md
> + - Poly modulus degree specified as 2^[x]
Does this program expect the string "2^10" or instead "1024"? If the latter, perhaps revise as 
```suggestion
- A power-of-two poly modulus degree specified e.g. "8192"
```

2021-09-09 14:32 UTC, fboemer commented on he-samples/examples/secure-query/README.md
> +The sample also supports specifying custom encryption parameters and input options. This can be useful to test more secure settings as well as to adjust keylength to support different database files.
We should be much more clear that this example does not guarantee any security level. Probably best to print the security level to the end user as well.

2021-09-09 16:24 UTC, ajagann commented on he-samples/examples/secure-query/README.md
> +For this example database keys are assumed to be char strings. With the default options they are encoded into 2 4bit chunks. This is done so that each chunk can be represented by the plain modulus of
or "4-bit"

2021-09-09 16:47 UTC, jobottle commented on he-samples/examples/secure-query/README.md
> +	Records searched per second: 0
Changed it, but open to any suggestions, ideally do not want any type of timing information even for example showing up in the documentation. I figured 0'ing it out would be ok but changed to descriptive text now.

2021-09-09 22:21 UTC, jobottle commented on he-samples/examples/secure-query/README.md
> +The sample also supports specifying custom encryption parameters and input options. This can be useful to test more secure settings as well as to adjust keylength to support different database files.
Added a blurb about the current security settings and a general warning/guideline, not sure if it would be preferable to add this information else where and/or extend it.

2021-09-10 14:22 UTC, fboemer commented on he-samples/examples/secure-query/README.md
> +- A power-of-two poly modulus degree specified as e.g. "10" for degree 1024=2^10
Nit: mismatched indent with next two lines

2021-09-10 14:32 UTC, faberga commented on he-samples/examples/secure-query/README.md
> +
This is a bit dry.  People are not understand what a chunk is and how the matching is done unless they go and look in the code which is not particularly well documented. I would suggest a two pronged approach: 1) document the code 2) extend the explanation here in the README and make reference to the code.

2021-09-10 14:36 UTC, faberga commented on he-samples/examples/secure-query/README.md
> +	Records searched per second: 0
the changes made are ok.

2021-09-10 21:47 UTC, fboemer approved these changes

2021-09-16 16:28 UTC, jlhcrawford approved these changes
Looks good. Thanks Jeremy!

2021-09-16 17:14 UTC, faberga submitted a review, later dismissed

2021-09-16 19:31 UTC, faberga commented
@jobottle I'm waiting for the tests to complete, to then approve.

2021-09-16 22:36 UTC, faberga approved these changes
Approved as it passed all the CI builds.

2021-09-17 11:07 UTC, merged