Improve psi example
intel/he-toolkit pull request #58
Opened 2022-01-14 21:54 UTC by denCalderon

Readme file and source code were updated to execute the example without issues.

2022-01-14 22:31 UTC, hamishun requested changes
Let's have talk about the script. It's a good idea to run the pre-commit before pushing.

2022-01-14 22:31 UTC, hamishun commented on .typos.toml
> +# typos cannot ignore specidfied files when used with pre-commit
```suggestion
# typos cannot ignore specified files when used with pre-commit
```

2022-01-14 22:31 UTC, hamishun commented on docker/welcome_msg.sh
> +     create a file with the data that the program will use as the client set.
```suggestion
  6. run_psi_example.sh: this will execute an example that uses the HElib library and the BGV scheme 
     to compute the intersection of two given sets. If the user wants, the script will also 
     create a file with the data that the program will use as the client set.  
```

2022-01-14 22:31 UTC, hamishun commented on he-samples/examples/psi/README.md
> +PSI example uses [HElib library](https://github.com/homenc/HElib) to compute intersection of two given sets that were encrypted with BGV scheme, so it will return all the elements that are common to
```suggestion
PSI example uses the [HElib library](https://github.com/homenc/HElib) to compute intersection of two given sets that were encrypted with the BGV scheme, so it will return all the elements that are common to both sets.
```

2022-01-14 22:31 UTC, hamishun commented on he-samples/examples/psi/README.md
> +The program reads words from client and server sets and computes a hash value for each word. The hash value, an integer binary representation is encoded as a polynomial with the coefficients in binar
```suggestion
The program reads words from the client and the server sets and computes a hash value for each word. The hash value, an integer binary representation, is encoded as a polynomial with the coefficients in binary {0,1}. 
```

2022-01-14 22:31 UTC, hamishun commented on docker/runners/run_psi_example.sh
> +echo "Executig the example"
```suggestion
echo "Executing the example"
```

2022-01-24 20:42 UTC, joserochh approved these changes
Good to go if CI runs ok

2022-01-24 21:34 UTC, hamishun requested changes
Some typos and rewording in the docs.

2022-01-24 21:34 UTC, hamishun commented on README.md
> +### Psi
```suggestion
### Private Set Intersection
```

2022-01-24 21:34 UTC, hamishun commented on README.md
> +    - [Psi](#psi)
```suggestion
    - [Private Set Intersection](#private-set-intersection)
```

2022-01-24 21:34 UTC, hamishun commented on README.md
> +The [psi](he-samples/examples/psi) example computes the intersection of two
```suggestion
The [Private Set Intersection (PSI)](he-samples/examples/psi) example computes the intersection of two
```

2022-01-24 21:34 UTC, hamishun commented on README.md
> +for usage information.
```suggestion
given sets. The program computes a hash value for each entry of both the client
and the server sets, then using the HElib BGV scheme, it encrypts the client
set and computes the intersection, returning all the encrypted elements that
are common to both sets. See the [README](he-samples/examples/psi/README.md)
for usage information.
```

2022-01-24 21:34 UTC, hamishun commented on docker/README.md
> +  [PSI](../he-samples/examples/psi).
```suggestion
  [Private Set Intersection](../he-samples/examples/psi).
```

2022-01-24 21:34 UTC, hamishun commented on he-samples/examples/psi/README.md
> +PSI example uses the [HElib library](https://github.com/homenc/HElib) to compute intersection of two given sets that were encrypted with the BGV scheme, so it will return all the elements that are co
```suggestion
The Private Set Intersection (PSI) example uses the [HElib library](https://github.com/homenc/HElib) to compute intersection of two given sets that were encrypted with the BGV scheme, so it will return all the elements that are common to both sets.

```

2022-01-24 21:34 UTC, hamishun commented on he-samples/examples/psi/README.md
> +## How it works
```suggestion
## Introduction
```

2022-01-24 21:34 UTC, hamishun commented on he-samples/examples/psi/README.md
> +The program reads words from the client and the server sets and computes a hash value for each word. The hash value, an integer binary representation, is encoded as a polynomial with the coefficients
```suggestion
The PSI program reads words from the client and the server sets and computes a hash value for each word. The hash value, an integer binary representation, is encoded as a polynomial with the coefficients in binary {0,1}.
```

2022-01-24 21:34 UTC, hamishun commented on he-samples/examples/psi/README.md
> +
```suggestion
## How It Works
```

2022-01-24 21:34 UTC, hamishun commented on he-samples/examples/psi/README.md
> +The encoded set for the client is encrypted, then intersection is computed and finally, the result is decrypted. The program keeps a translation table for the client set of which hashes goes with whi
```suggestion
The encoded set for the client is encrypted, then the intersection is computed and finally the resultant set intersection is decrypted. The program keeps a translation table for the client set of which hash goes with which word, so that the returned hashes can be translated back to words.
```

2022-01-24 21:34 UTC, hamishun commented on he-samples/examples/psi/README.md
> +The maximum number of entries that the client set supports is the number of slots in the plaintext/ciphertext.
```suggestion
The maximum number of entries that the client set supports is the number of slots in the plaintext.
```

2022-01-25 18:23 UTC, jlhcrawford requested changes
In general this looks good except for some minor comments on documentation.
There are some minor typos/rewording of the README documentation.

2022-01-25 18:23 UTC, jlhcrawford commented on he-samples/examples/psi/README.md
> +The plaintext prime in this example is always 2 and the maximum size of these polynomials are the order of p in Z_{m}^{\*}/\<p\> quotient group.
```suggestion
The plaintext prime in this example is always 2 and the maximum size of these polynomials are the order of p in the Z_{m}^{\*}/\<p\> quotient group.
```

2022-01-25 18:23 UTC, jlhcrawford commented on he-samples/examples/psi/README.md
> +There are three sets to choose from of differing sizes under [datasets](./datasets) folder. The default is `fruits.set`, but it can be changed executing:
```suggestion
There are three sets to choose from of differing sizes under the [datasets](./datasets) folder. The default is `fruits.set`, but it can be changed executing:
```

2022-01-25 18:23 UTC, jlhcrawford commented on he-samples/examples/psi/README.md
> +The default order of the cyclotomic polynomial used in the BGV scheme is 771 which gives a ord(p) = 16. You can change the default `m` by running:
```suggestion
The default order of the cyclotomic polynomial used in the BGV scheme is 771 which gives ord(p) = 16, where p = 2. You can change the default `m` by running:
```

2022-01-25 18:23 UTC, jlhcrawford commented on he-samples/examples/psi/README.md
> +Although this usually means increasing the number of bits for HElib to handle noise at larger m values.
```suggestion
Although, this usually coincides with needing to increase the number of bits for HElib to handle the increased noise level at larger m values.
```

2022-01-25 18:23 UTC, jlhcrawford commented on he-samples/examples/psi/psi.cpp
> +static inline NTL::ZZX long_to_poly(long x, long N) {
Maybe have a short description of what this function does? What are the inputs/outputs?

2022-01-25 18:23 UTC, jlhcrawford commented on he-samples/examples/psi/psi.cpp
> +static inline long poly_to_long(const NTL::ZZX& poly, long N) {
Same as above comment. Description?

2022-01-25 18:23 UTC, jlhcrawford commented on he-samples/examples/psi/psi.cpp
> +TranslationTable* read_in_set(std::vector<NTL::ZZX>& out,
Same as above comment. Description?

2022-01-27 15:26 UTC, hamishun approved these changes
LG

2022-01-27 15:34 UTC, merged