Docker build supported on macOS Catalina
intel/he-toolkit pull request #60
Opened 2022-01-27 18:35 UTC by jlhcrawford

Docker build now works on macOS Catalina (10.15.7).
Includes other bug fixes to docker build and documentation updates.

2022-01-27 18:56 UTC, hamishun requested changes

2022-01-27 18:56 UTC, hamishun commented on docker/setup_and_run_docker.sh
> +    --build-arg GID="1000" \
Is hardcoding going to solve our issue here?

2022-01-27 18:58 UTC, jlhcrawford commented on docker/setup_and_run_docker.sh
> +    --build-arg GID="1000" \
I built the docker on both my Mac and the Ubuntu server and confirmed I could still run the tests and example scripts inside the container.

2022-01-28 12:47 UTC, jlhcrawford commented on docker/setup_and_run_docker.sh
> +    --build-arg GID="1000" \
Extra logic has been added to force the IDs on MacOS to 1000 by default.
Linux logic is now unchanged.

2022-01-28 12:58 UTC, hamishun approved these changes
LG

2022-01-28 16:34 UTC, merged