Den calderon/unit test
intel/he-toolkit pull request #67
Opened 2022-02-18 17:53 UTC by denCalderon

Unit and functional testing

2022-02-22 15:42 UTC, hamishun commented on kit/command_list.py
> +from toml import load
Is there an advantage here stripping toml module object from load. load loses context when it is called. 
Compare load(...) vs toml.load(...). The latter is self documenting.

2022-02-22 23:08 UTC, denCalderon commented on tests/test_comp_builder.py
> +def test_chain_run_all_failure(mocker, funcs_failire):
updated

2022-02-23 14:55 UTC, hamishun requested changes
Minor tweak

2022-02-23 15:57 UTC, hamishun approved these changes

2022-02-23 15:58 UTC, jlhcrawford approved these changes

2022-02-23 15:58 UTC, merged