Den calderon/docker
intel/he-toolkit pull request #68
Opened 2022-02-21 21:23 UTC by denCalderon

Using hekit.py on the docker build

2022-02-22 16:24 UTC, hamishun requested changes

2022-02-22 17:58 UTC, hamishun requested changes

2022-02-22 17:58 UTC, hamishun commented on kit/command_install.py
>              print(f"Skipping", comp_label)
```suggestion
            print("Skipping", comp_label)
```

2022-02-22 17:58 UTC, hamishun commented on docker/setup_and_run_docker.sh
> +
This can be brought in to parts.tar.gz

2022-02-22 19:57 UTC, denCalderon commented on docker/setup_and_run_docker.sh
> +
Updated as it was requested

2022-02-22 20:39 UTC, hamishun approved these changes
LG

2022-02-22 20:45 UTC, jlhcrawford requested changes
The rule for the copyright years is they should be from the year the file came into existence.

2022-02-22 20:45 UTC, jlhcrawford commented on kit/hekit.py
> +# Copyright (C) 2020 Intel Corporation
```suggestion
# Copyright (C) 2021 Intel Corporation
```

2022-02-22 20:45 UTC, jlhcrawford commented on recipes/default.toml
> +# Copyright (C) 2020 Intel Corporation
```suggestion
# Copyright (C) 2022 Intel Corporation
```

2022-02-22 20:45 UTC, jlhcrawford commented on recipes/test.toml
> +# Copyright (C) 2020 Intel Corporation
```suggestion
# Copyright (C) 2022 Intel Corporation
```

2022-02-23 14:21 UTC, jlhcrawford approved these changes

2022-02-23 14:21 UTC, merged