Tab completion
intel/he-toolkit pull request #74
Opened 2022-02-28 21:47 UTC by denCalderon

2022-03-01 17:42 UTC, hamishun requested changes
Where is the documentation in the README.md?

2022-03-01 17:42 UTC, hamishun commented on kit/hekit.py
> +
```suggestion
def components_completer(prefix, parsed_args, **kwargs):
    parsed_args.config = load_config(parsed_args.config)
    return get_components(parsed_args.config.repo_location)


def instances_completer(prefix, parsed_args, **kwargs):
    parsed_args.config = load_config(parsed_args.config)
    comp_name_path = f"{parsed_args.config.repo_location}/{parsed_args.component}"
    return get_instances(comp_name_path)

```

2022-03-01 17:42 UTC, hamishun commented on kit/hekit.py
> +def parse_components(prefix, parsed_args, **kwargs):
These new functions could be placed into their own module and included if the autocomplete is successful in the try block

2022-03-01 17:42 UTC, hamishun commented on kit/hekit.py
> +    ).completer = parse_instances
Will this not complain if the argcomplete fails to import?

2022-03-01 20:06 UTC, denCalderon commented on kit/hekit.py
> +def parse_components(prefix, parsed_args, **kwargs):
They were moved to tab_completion.py

2022-03-01 20:07 UTC, denCalderon commented on kit/hekit.py
> +
updated as requested

2022-03-01 20:12 UTC, denCalderon commented on kit/hekit.py
> +    ).completer = parse_instances
I tested on the duckers build were argcomplete is not installed, and the python program can be executed correctly,  but it requires than the functions  (parse_components and parse_instances) were declared

2022-03-02 21:46 UTC, hamishun requested changes

2022-03-02 21:46 UTC, hamishun commented on kit/tab_completion.py
> +
This line is probably not required

2022-03-03 15:13 UTC, denCalderon commented on kit/tab_completion.py
> +
It was deleted

2022-03-04 11:44 UTC, jlhcrawford requested changes
This is a general comment on the python code. I know most of the functions have self-documenting names but it's good practice to still have a comment documenting what the function does. This can be a few words or a sentence in a docstring at the top of the function.

2022-03-04 11:44 UTC, jlhcrawford commented on kit/tab_completion.py
> +    except ImportError:
Maybe add a comment here or where this function is called saying argcomplete is optional. It's unusual to catch an exception and then pass.

2022-03-04 17:19 UTC, denCalderon commented on kit/tab_completion.py
> +    except ImportError:
new comments were addes

2022-03-04 18:19 UTC, hamishun requested changes

2022-03-04 18:19 UTC, hamishun commented on kit/command_init.py
> +
The test of argcomplete should not be in python it should be in POSIX shell if statement.
That way when a user decided afterwards that they suddenly do want tab completion they do not require to rerun hekit init.
```suggestion
    # 2-Register hekit link and hekit.py script to enable tab completion
    if not util.find_spec("argcomplete") == None:
        register_py = f'eval "$(register-python-argcomplete hekit.py)"'
        register_link = f'eval "$(register-python-argcomplete hekit)"'
        content = "\n".join([content, register_py, register_link])

```

2022-03-04 18:39 UTC, jlhcrawford commented on docker/Dockerfile.base
> +    pip install argcomplete
We can use a requirements file and specify minimum versions since the number of python dependencies has doubled.

2022-03-04 20:51 UTC, hamishun approved these changes

2022-03-04 20:53 UTC, merged