Back substitution with !!
intel/he-toolkit pull request #78
Opened 2022-03-07 22:17 UTC by denCalderon

2022-03-09 16:26 UTC, hamishun requested changes

2022-03-09 16:26 UTC, hamishun commented on kit/spec.py
> +    def from_toml_file(cls, filename: str, rloc: str, recipe_arg: str):
At this point, shouldn't recipe_arg already been parsed? so that it is a nice obj like a dict?

2022-03-09 17:49 UTC, denCalderon commented on kit/spec.py
> +    if isinstance(recipe_arg, str):
this is the case when the user does not use recipe_arg, the value will be None.

2022-03-09 18:22 UTC, denCalderon commented on tests/test_spec.py
> +    spec = Spec.from_instance_spec("hexl", expected["hexl"][0], "", None)
updatated

2022-03-09 18:23 UTC, denCalderon commented on tests/test_spec.py
> +    spec_generator = Spec.from_toml_file(filepath, "", None)
updated

2022-03-09 21:47 UTC, denCalderon commented on kit/spec.py
> +                raise InvalidSpec(f"Wrong format for {key_value}. Expected key=value")
udpated to ValueError

2022-03-09 21:47 UTC, denCalderon commented on kit/spec.py
> +    def from_toml_file(cls, filename: str, rloc: str, recipe_arg: str):
updated

2022-03-10 15:47 UTC, jlhcrawford approved these changes

2022-03-10 17:29 UTC, hamishun requested changes

2022-03-10 17:29 UTC, hamishun commented on kit/hekit.py
> +        return {}
This should raise a TypeError with some f-string if possible to say f"Input type is {type(recipe_arg)}, but should be type str". The argparser will handle the default of an empty dictionary.

2022-03-10 17:38 UTC, jlhcrawford requested changes
I have suggested typo fixes and re-wording of the documentation.

2022-03-10 17:38 UTC, jlhcrawford commented on kit/README.md
> +`install RECIPE_FILE`: Installs components defined in [recipen file](#recipe-file).
```suggestion
`install RECIPE_FILE`: Installs components defined in [recipe file](#recipe-file).
```

2022-03-10 17:38 UTC, jlhcrawford commented on kit/README.md
> +`build RECIPE_FILE`: Builds components defined in [recipen file](#recipe-file).
```suggestion
`build RECIPE_FILE`: Builds components defined in [recipe file](#recipe-file).
```

2022-03-10 17:38 UTC, jlhcrawford commented on kit/README.md
> +`fetch RECIPE_FILE`: Fetches components defined in [recipen file](#recipe-file).
```suggestion
`fetch RECIPE_FILE`: Fetches components defined in [recipe file](#recipe-file).
```

2022-03-10 17:38 UTC, jlhcrawford commented on kit/README.md
> +where the options and the inputs files are explained in the following sections.
```suggestion
where the options and input files are explained in the following sections.
```

2022-03-10 17:38 UTC, jlhcrawford commented on kit/README.md
> +`--recipe_arg "key=value"`: Optional argument to replace data marked as !key! in a [recipen file](#recipe-file).
```suggestion
`--recipe_arg "key=value"`: Optional argument to replace data marked as !key! in a [recipe file](#recipe-file).
```

2022-03-10 17:38 UTC, jlhcrawford commented on kit/README.md
> +The recipe File is a TOML file that defines the libraries and the required actions to install them, as shown in the following example:
```suggestion
The recipe file is a TOML file that defines the libraries and the required actions to install them, as shown in the following example:
```

2022-03-10 17:38 UTC, jlhcrawford commented on kit/README.md
> +The [recipes](../recipes/) directory contains the usual files to set up a working enviroment.
```suggestion
The [recipes](../recipes/) directory contains default recipes for setting up a working environment.
```

2022-03-10 17:38 UTC, jlhcrawford commented on kit/README.md
> +#### Back Sustitution in a recipe file
```suggestion
#### Back Substitution in a recipe file
```

2022-03-10 17:38 UTC, jlhcrawford commented on kit/README.md
> +The specfic value of a pair (key = "value") in the recipe file can be reuse in others sections of the file. That can be achieved using the following options:
```suggestion
The value of the pair (key = "value") in the recipe file can be reused in other sections of the file. This can be achieved using the following options:
```

2022-03-10 17:38 UTC, jlhcrawford commented on kit/README.md
> +$key$ : similar as %key%, but it must be used when replacing dependecies.
```suggestion
$component/instance/key$ : back substitutes the `key` from a specific instance.
```

2022-03-10 17:38 UTC, jlhcrawford commented on kit/README.md
> +!key! : it will be replaced with a string defined from a external source. If --recipe_arg is not set, there will be a prompt message asking about it.
```suggestion
!key! : back substitute a value defined from an external source. If `--recipe_arg` is not set, the user will be prompted to provide a value.
```

2022-03-10 17:38 UTC, jlhcrawford commented on kit/README.md
> +%key% : it will be replaced with the string value of a key defined in the same section.
```suggestion
%key% : back substitute a value from within the same instance.
```

2022-03-10 18:38 UTC, denCalderon commented on kit/hekit.py
> +        return {}
Code is not needed so it was deleted

2022-03-10 20:03 UTC, hamishun approved these changes

2022-03-10 21:03 UTC, jlhcrawford approved these changes

2022-03-10 21:04 UTC, merged