Checking if the recipes are unique
intel/he-toolkit pull request #97
Opened 2022-04-22 20:42 UTC by denCalderon

It is possible to have different recipes with the same name.
Check if they are the same or not. If they are not the same throw an error, otherwise ignore the duplicate.

2022-05-04 15:20 UTC, jlhcrawford commented on tests/test_spec.py
> +    if hekit.spec files does not exist"""
```suggestion
    if hekit.spec file does not exist"""
```

2022-05-05 17:27 UTC, hamishun requested changes

2022-05-05 17:27 UTC, hamishun commented on kit/spec.py
> +    @classmethod
Is this a classmethod using cls or staticmethod? cls doesnt seem to be used.

2022-05-06 13:50 UTC, hamishun submitted a review, later dismissed

2022-05-08 13:44 UTC, jlhcrawford approved these changes

2022-05-08 13:47 UTC, merged